apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-dep
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx-demo:v1.0
          ports:
            - containerPort: 80